---
language: objective-c

before_install:
  - gem install cocoapods
  - sudo easy_install cpp-coveralls

script:
  - xctool -workspace 'Masonry.xcworkspace' -scheme 'Masonry iOS' -configuration Debug -sdk iphonesimulator7.0 clean build test -freshSimulator -freshInstall
  - xctool -workspace 'Masonry.xcworkspace' -scheme 'Masonry Mac' -configuration Debug -sdk macosx10.8 clean build test 

after_success:
  - ./script/coveralls.sh
