---
language: objective-c

before_install:
  - gem install cocoapods
  - sudo easy_install cpp-coveralls

script:
  - xctool -workspace 'Masonry.xcworkspace' -scheme 'Masonry iOS Tests' -configuration Debug -sdk iphonesimulator7.0 clean build test -freshSimulator -freshInstall

after_success:
  - ./script/coveralls.sh
